name: tests-securities

on:
  pull_request:
    path:
      - 'securities/**'

jobs:
  build:  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && npm install 
